version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/node:16
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASS
    steps:
        - checkout
        - run:
            name: Publish to NPM
            command: |
              npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
              npm publish

workflows:
  tagged-build:
    jobs:
        - publish:
            filters:
              tags:
                only: /[0-9]+(\.[0-9]+)*/